title: my deviations
author:
  name: Señor Gus (SrfRoG)
  email: hello@srfrog.dev
description: >
  Posts about technology, privacy, and history.
  Mostly random disconnected thoughts.
  You should apply your favorite power function to interpret.

remote_theme: jekyll/minima
show_excerpts: false

minima:
  skin: dark
  social_links:
    github: srfrog
